#!/usr/bin/env python3
"""Build RATING.md from the P2 turn-rule files (live and hist).

Run from /home/joe/code/futon2:
  python3 holes/labs/wm-contract/E-cascade-real/rules-from-turns/build_rating.py
Read-only on the rule files, the analysis records and the pattern library.
The pattern conclusion shown is read from the library file (continuation
lines included), not from the rule's :reading, because 18 live readings
quote an empty conclusion (the conclusion text sits on the next line).
"""
import glob, json, os, subprocess

BASE = "holes/labs/wm-contract/E-cascade-real/rules-from-turns"
LIB = "/home/joe/code/futon3/library"


def edn(path):
    out = subprocess.check_output(
        ["bb", "-e", f'(println (cheshire.core/generate-string (clojure.edn/read-string {{:default tagged-literal}} (slurp "{path}"))))'])
    return json.loads(out)


def conclusion(pid):
    lines = open(f"{LIB}/{pid.lstrip(':')}.flexiarg", encoding="utf-8").read().splitlines()
    for i, line in enumerate(lines):
        if line.lstrip().startswith("! conclusion:"):
            text = line.split("! conclusion:", 1)[1].strip()
            j = i + 1
            while j < len(lines) and lines[j].startswith("  ") and not lines[j].lstrip().startswith("+"):
                text += " " + lines[j].strip()
                j += 1
            return text.strip()
    return "(no conclusion line)"


def cell(s):
    return " ".join(str(s).split()).replace("|", "\\|")


def statements(ids, tokens):
    return "; ".join(tokens.get(t, {}).get("statement", t) for t in sorted(ids)) or "—"


rows = []
for s in ("live", "hist"):
    for f in sorted(glob.glob(f"{BASE}/{s}/*.edn")):
        d = edn(f)
        rec = d["source-record"]
        rec = rec if rec.startswith("/") else "/home/joe/code/" + rec
        src = json.load(open(rec))["source_text"]
        for r in d["rules"]:
            a, b = r["from"]["fragment"]
            rows.append((s, d["turn"], src[a:b], r["pattern"].lstrip(":"), conclusion(r["pattern"]),
                         statements(r["guard"]["needs"], d["tokens"]),
                         statements(r["guard"].get("forbids", []), d["tokens"]),
                         statements(r["produces"], d["tokens"])))

out = [
    "# P2 rating sheet — production rules written from claude-1's turn interpretations",
    "",
    "Generated by `build_rating.py`. Live set: kimi-2, `a30ab5ed`. Historical block 0: kimi-3, `4e297a30`.",
    "Each row is one rule: the fragment of Joe's turn, the pattern level 1 cited, the pattern's own",
    "conclusion (read from the library), and the rule as needs → produces (forbids where present).",
    "Rating column is blank for Joe. Suggested scale: 2 = the rule says what the pattern does here;",
    "1 = right pattern, rule off; 0 = wrong pattern or not an act (a stance, a verdict, a report).",
    "",
    "Known input defect: 5 fragments (live turns 1QzzO5, A8Ioc3, unzcX9) start or end mid-word.",
    "The spans are faithful to the level-1 analysis records, whose own fragmentation cut there.",
    "Both seats wrote 0 not-a-rule entries: every cited pattern was kept as a rule.",
    "",
    "| # | set | turn | fragment | pattern | pattern conclusion | needs | forbids | produces | rating |",
    "|---|---|---|---|---|---|---|---|---|---|",
]
for i, (s, t, frag, pid, concl, needs, forbids, prod) in enumerate(rows, 1):
    out.append(f"| {i} | {s} | {cell(t)} | {cell(frag)} | `{pid}` | {cell(concl)} | {cell(needs)} | {cell(forbids)} | {cell(prod)} |  |")
open(f"{BASE}/RATING.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print(len(rows), "rows")
