#!/usr/bin/env bb
(require '[clojure.edn :as edn] '[clojure.java.io :as io]
         '[clojure.pprint :as pprint] '[clojure.string :as str])
(import '[java.security MessageDigest])
(def home (System/getProperty "user.home"))
(def lab (str home "/code/futon2/holes/labs/wm-contract"))
(def artifacts (str home "/code/futon2/holes/labs/M-f11-find-production-successor"))
(def conf-path (or (System/getenv "F11_CONF") (str home "/code/mathlib4/DarkTower/WarMachine/F11AppliedConformance.lean")))
(def holes-path (or (System/getenv "F11_HOLES") (str home "/code/mathlib4/DarkTower/WarMachine/Holes.lean")))
(def live-path (or (System/getenv "F11_LIVE") (str artifacts "/applied-find.edn")))
(def acceptance-path (or (System/getenv "F11_ACCEPTANCE") (str artifacts "/acceptance.edn")))
(def out-path (or (System/getenv "F11_OUT") (str lab "/runs/F11-find/04-conformance.edn")))
(defn die [message data] (binding [*out* *err*] (println "f11-conformance:" message (pr-str data))) (System/exit 1))
(defn read-source [path kind] (if (.isFile (io/file path)) (slurp path) (die "file not found" {:kind kind :path path})))
(defn sha256 [path] (let [md (MessageDigest/getInstance "SHA-256")]
  (with-open [in (io/input-stream path)] (.update md (.readAllBytes in)))
  (apply str (map #(format "%02x" (bit-and 255 %)) (.digest md)))))
(defn code-only [s] (-> s (str/replace #"(?s)/--.*?-/" " ") (str/replace #"(?s)/-!.*?-/" " ")))
(def holes (read-source holes-path :holes))
(def code (code-only (read-source conf-path :applied-conformance)))
(def live (edn/read-string (read-source live-path :applied-run)))
(def acceptance (edn/read-string (read-source acceptance-path :acceptance)))
(def opaque-signature? (boolean (re-find #"(?s)opaque find \{State P Clause AsOf TextCitation : Type\*\}\s*:\s*FindQuery State P\s*→\s*\(R : Repository P\)\s*→\s*FindResult P Clause AsOf TextCitation R" holes)))
(def declarations ["def model " "def expected " "def validText " "theorem modelContainment" "theorem modelTypedAbsence" "theorem modelContentF2" "theorem modelCitationF3" "theorem modelExclusionF4" "theorem modelDiscriminatingF4" "theorem conformantImplementationExists"])
(def source-pins ["d4b59fe05b98d0a3faa041714e0ea05a9ac11feaa1997efcff1da17db7288733" "4293feb4d644d7d6661a622839b156ecc8a89e56a3bc3c66858a351a6feb30f6" "2e12af8463e82db8333157f79448b911ead1bcc71b5ca25e8510d8463757bdc9"])
(def scenarios (:scenarios live))
(def scenario-facts (mapv (fn [s] (let [z (get-in s [:f4 :zero-mass-pattern])]
  (sorted-map :scenario [(:treatment s) (:disposition s)] :zero-mass z
              :zero-mass-selected? (contains? (set (:selected-union s)) z)
              :f4-holds? (true? (get-in s [:f4 :holds]))))) scenarios))
(def measured (sorted-map :pattern-count (count (:repository live)) :scenario-count (count scenarios)
  :round-count (reduce + (map #(count (:round-results %)) scenarios))
  :f4-passes (count (filter :f4-holds? scenario-facts)) :drift-mismatches (get-in live [:drift :mismatch-count])))
(def missing-declarations (vec (remove #(str/includes? code %) declarations)))
(def missing-source-pins (vec (remove #(str/includes? code %) source-pins)))
(def sorry-free? (not (re-find #"\bsorry\b|\badmit\b|\bsorryAx\b|\bnative_decide\b|(?m)^axiom\b" code)))
(def problems (cond-> []
  (not opaque-signature?) (conj [:signature-drift])
  (seq missing-declarations) (conj (into [:missing-declarations] missing-declarations))
  (seq missing-source-pins) (conj (into [:source-pin-drift] missing-source-pins))
  (not sorry-free?) (conj [:sorry-or-axiom-in-conformance-file])
  (not= {:pattern-count 24 :scenario-count 6 :round-count 34 :f4-passes 6 :drift-mismatches 0} measured) (conj [:runtime-measurement-drift measured])
  (some :zero-mass-selected? scenario-facts) (conj [:zero-mass-was-selected (mapv :scenario (filter :zero-mass-selected? scenario-facts))])
  (not= (get-in acceptance [:artifacts :result-sha256]) (sha256 live-path)) (conj [:artifact-digest-drift])))
(def result (sorted-map :schema :wm/f11-conformance-gate-v2 :authority {:holes holes-path :applied-conformance conf-path}
  :opaque-signature? opaque-signature? :required-declarations (into (sorted-map) (map (fn [x] [x (str/includes? code x)])) declarations)
  :required-source-pins (into (sorted-map) (map (fn [x] [x (str/includes? code x)])) source-pins)
  :sorry-free? sorry-free? :runtime measured :scenarios scenario-facts :result-sha256 (sha256 live-path) :problems problems))
(io/make-parents out-path) (spit out-path (with-out-str (pprint/pprint result)))
(if (seq problems) (do (binding [*out* *err*] (println "f11-conformance: FAIL" (pr-str problems))) (System/exit 1))
  (println "f11-conformance: PASS -- applied signature, pins, declarations and fresh runtime agree"))
