#!/usr/bin/env bb
(require '[clojure.edn :as edn]
         '[clojure.java.io :as io]
         '[clojure.java.shell :as shell]
         '[clojure.string :as str])

(def here (.getParentFile (.getAbsoluteFile (io/file *file*))))
(def repo (.getCanonicalFile (io/file here "../../..")))
(def worklist-path (io/file here "worklist.edn"))
(def patterns-dir (io/file (or (System/getenv "WM_PATTERNS_DIR")
                               (str (io/file repo "../futon3/library/apparatus")))))
(def output-path (io/file here "dependency-frontier.md"))
(defn die [& xs] (binding [*out* *err*] (apply println "dependency-frontier:" xs)) (System/exit 1))
(defn sha [f]
  (let [{:keys [exit out err]} (shell/sh "sha256sum" (.getPath f))]
    (when-not (zero? exit) (die "cannot hash" (.getPath f) err))
    (first (str/split out #"\s+"))))
(defn sig [f]
  (or (some->> (str/split-lines (slurp f))
               (some #(when (str/starts-with? % "@violation-signature ")
                        (subs % (count "@violation-signature ")))))
      (die "pattern lacks @violation-signature" (.getName f))))
(def patterns
  (->> (.listFiles patterns-dir)
       (filter #(str/ends-with? (.getName %) ".flexiarg"))
       (map (fn [f] {:pattern (str "apparatus/" (str/replace (.getName f) #"\.flexiarg$" ""))
                     :signature (sig f)}))
       (sort-by :pattern)
       vec))
(def w (edn/read-string (slurp worklist-path)))
(def items (:items w))
(def idx (into {} (map (juxt :id identity) items)))
(doseq [i items d (:depends-on i)]
  (when-not (idx d) (die (:id i) "names unknown dependency" d)))
(defn visit [id visiting visited]
  (cond (visited id) visited
        (visiting id) (die "dependency cycle at" id)
        :else (reduce (fn [v d] (visit d (conj visiting id) v))
                      (conj visited id) (:depends-on (idx id)))))
(reduce (fn [v id] (visit id #{} v)) #{} (keys idx))

(def assurances (mapcat (fn [i] (map #(assoc % :ticket (:id i)) (:assures i))) items))
(doseq [a assurances]
  (doseq [k [:pattern :signature :state]]
    (when-not (contains? a k) (die (:ticket a) "assurance lacks" k)))
  (when-not (#{:witnessed :ticketed :not-applicable} (:state a))
    (die (:ticket a) "unknown assurance state" (:state a)))
  (when (and (= :witnessed (:state a))
             (not (and (string? (get-in a [:witness :mechanism-sha]))
                       (string? (get-in a [:witness :run])))))
    (die (:ticket a) "witnessed assurance lacks mechanism-sha/run")))
(def expected (into {} (map (juxt :pattern :signature) patterns)))
(def grouped (group-by :pattern assurances))
(doseq [[pattern signature] expected]
  (let [covered (grouped pattern)]
    (when-not (= 1 (count covered))
      (die "uncovered or multiply-covered pattern/signature pair" (pr-str [pattern signature])))
    (when-not (= signature (:signature (first covered)))
      (die "assurance signature is not the pattern clause" pattern))))
(doseq [pattern (keys grouped)]
  (when-not (expected pattern) (die "assurance names unknown pattern/signature pair" pattern)))

;; A witnessed mechanism is current only while its pinned blob still exists in
;; the repository. A moved mechanism is rendered ticketed, never witnessed.
(defn live-state [a]
  (if (= :witnessed (:state a))
    (let [{:keys [path mechanism-sha]} (:witness a)
          f (when path (io/file repo path))]
      (if (and f (.isFile f) (= mechanism-sha (sha f))) :witnessed :ticketed))
    (:state a)))
(defn dep-depth [id]
  (if-let [ds (seq (:depends-on (idx id)))]
    (inc (apply max (map dep-depth ds))) 0))
(def ordered (sort-by (juxt #(dep-depth (:id %)) #(str (:id %))) items))
(def rendered
  (str "# WM dependency and assurance frontier\n\n"
       "GENERATED by `gen_dependency_frontier.bb`; do not edit. The worklist tickets are authoritative.\n\n"
       "## Dependency-first worklist\n\n"
       "| depth | ticket | status | depends on |\n|---:|---|---|---|\n"
       (apply str (for [i ordered]
                    (format "| %d | `%s` | `%s` | %s |\n" (dep-depth (:id i)) (:id i) (:status i)
                            (if (seq (:depends-on i)) (str/join ", " (map #(str "`" % "`") (:depends-on i))) "—"))))
       "\n## Generated pattern → tickets index\n\n"
       "| pattern | state | ticket | violation-signature clause |\n|---|---|---|---|\n"
       (apply str (for [p patterns
                        :let [a (first (grouped (:pattern p)))]]
                    (format "| `%s` | `%s` | `%s` | %s |\n"
                            (:pattern p) (live-state a) (:ticket a)
                            (str/replace (:signature p) "|" "\\|"))))))
(if (= "--check" (first *command-line-args*))
  (do (when-not (and (.isFile output-path) (= rendered (slurp output-path)))
        (die "generated artifact is stale; run bb gen_dependency_frontier.bb"))
      (println "dependency-frontier: current --" (count items) "tickets and" (count patterns) "pattern/signature pairs"))
  (do (spit output-path rendered)
      (println "dependency-frontier: wrote" (.getPath output-path) "with" (count items) "tickets and" (count patterns) "pattern/signature pairs")))
