import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 } });
const page = await ctx.newPage();
const logs = [];
page.on('console', m => logs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', e => logs.push(`[PAGEERR] ${e.message}`));
page.on('requestfailed', r => logs.push(`[REQFAIL] ${r.url()} ${r.failure()?.errorText}`));
await page.goto('http://localhost:8710/index.html', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(5000);
const title = await page.title();
const body = await page.evaluate(() => document.body.innerText.slice(0, 1500));
const testids = await page.evaluate(() => Array.from(document.querySelectorAll('[data-testid]')).map(e => e.getAttribute('data-testid')));
const svgCount = await page.locator('svg').count();
console.log('title:', title);
console.log('svg count:', svgCount);
console.log('testids:', testids);
console.log('body text (1500):\n', body);
console.log('\nconsole/errors (first 30):');
logs.slice(0, 30).forEach(l => console.log(' ', l));
await page.screenshot({ path: '/tmp/wm-probe.png', fullPage: true });
console.log('\nscreenshot saved /tmp/wm-probe.png');
await browser.close();
