;; IS cascade*a SATISFIABLE? — checking the constraint instead of iterating it.
;;
;; check_cascade_times_arm.clj ITERATES g[s(b)] := nu(g[b]) and reports the orbit.
;; Under the propagator reading it "settled to PERIOD 1" for every arm, which I
;; was about to report as a result. It is an ARTEFACT OF MY OWN `step`:
;;
;;   (reduce (fn [acc b] (assoc acc (s b) (nu (g b)))) g BINS)
;;
;; s is NON-INJECTIVE — s(:dead) = s(:collapsing) = :dead — so two constraints
;; write the same cell and LAST WRITE WINS. The reduce silently picks a winner by
;; seq order. It cannot report a contradiction because assoc has no way to
;; disagree. "It settled" meant "my fold ran out of bins", not "the system has a
;; solution". check_tokamak_cascade.clj:56 has the SAME `step` and the same hole.
;;
;; The constraint is: for EVERY b,  g[s(b)] = nu(g[b]).  Solve it, don't fold it.
;;
;; Run: bb check_cascade_sat.clj

(require '[clojure.edn :as edn] '[clojure.string :as str])

(def C (edn/read-string (slurp "cascade-tokamak-v0.edn")))
(def BINS (get-in C [:cascade/carrier :N :elements]))
(def g0 (:cascade/policy C))

(def positional
  {:rotate+2   [2 3 4 5 6 7 0 1]
   :three+five [1 2 0 4 5 6 7 3]
   :sigma-5127 [5 1 2 7 6 0 4 3]
   :rotate+1   [1 2 3 4 5 6 7 0]
   :identity   [0 1 2 3 4 5 6 7]})
(def ACTS (vec (keys positional)))
(defn compose [a b] (mapv #(nth a %) b))

(def order-bins (vec BINS))
(def s-shift (zipmap order-bins (cons (first order-bins) (butlast order-bins))))

(println "=== s : BINS -> BINS  (emacsShift, k |-> max(k-1,0), on the regime scale)")
(doseq [b BINS] (println (format "    %-12s -> %-12s %s" b (s-shift b)
                                 (if (= b (s-shift b)) "  <- SELF-LOOP" ""))))
(println "    image(s) =" (pr-str (vec (distinct (vals s-shift)))))
(println "    FREE     =" (pr-str (vec (remove (set (vals s-shift)) BINS))))

;; ---- the self-loop is the whole story --------------------------------------
(println "\n=== THE UNSAT CORE, derived before any search")
(println "    s(:dead) = :dead is a SELF-LOOP. Its constraint reads")
(println "        g[:dead] = nu(g[:dead])")
(println "    i.e. g[:dead] must be a FIXED POINT of nu.")
(println "    But nu_a = left-multiplication by a, and Cayley says nu_a has a fixed")
(println "    point iff a = identity. So for EVERY a /= identity the self-loop is")
(println "    UNSATISFIABLE — and for a = identity it is satisfiable only because")
(println "    nu = id rewrites nothing.")
(println "    The clamp IS the self-loop: max(k-1,0) fixes 0, and 0 is :dead.")

;; ---- now actually search, over the full symmetric group of reachable values --
;; Values range over the group generated by the arms (closure), not just the 5.
;; BFS over generators. My first version took the all-pairs product of `seen` with
;; itself each round — |G|^2 per round on a group that turns out to be most of S_8.
;; It did not finish in 120s. Multiplying only by GENERATORS reaches the same
;; closure in |G|*|gens| steps.
(defn closure [gens]
  (loop [seen (set gens) frontier (vec gens)]
    (if (empty? frontier)
      seen
      (let [nxt (for [x frontier a gens :let [y (compose a x)] :when (not (seen y))] y)]
        (recur (into seen nxt) (vec (distinct nxt)))))))
(def G (closure (vec (vals positional))))
(println (format "\n=== the group generated by the five arms: |G| = %d" (count G)))
(println "    (P as written is 5 elements and is NOT closed under composition —")
(println "     cascade*a leaves the vocabulary on the first step. The honest value")
(println "     domain for the rewrite is this closure.)")

(defn sat? [a]
  ;; brute force over assignments BINS -> G is |G|^5 — too big. But the shape is a
  ;; chain rooted at FREE, so: choose g[:rich] freely, propagate, then CHECK every
  ;; constraint including the self-loop. Any violation = unsat for that root.
  (let [nu #(compose (positional a) %)]
    (some (fn [root]
            (let [g (-> {} (assoc :rich root)
                        (assoc :mid  (nu root))
                        (assoc :lean (nu (nu root)))
                        (assoc :collapsing (nu (nu (nu root))))
                        (assoc :dead (nu (nu (nu (nu root))))))]
              (when (every? (fn [b] (= (g (s-shift b)) (nu (g b)))) BINS)
                g)))
          G)))

(println "\n=== SEARCH: is there ANY g : BINS -> G with g[s(b)] = nu_a(g[b]) for all b?")
(doseq [a ACTS]
  (let [r (sat? a)]
    (println (format "    cascade*%-12s %s" a
                     (if r (str "SAT, e.g. " (pr-str (into (sorted-map) r)))
                         (format "UNSAT over all %d candidate roots" (count G)))))))

(println "\n=== WHAT THIS MEANS FOR 'cascade * rotate+2'")
(println "    Under the PROPAGATOR reading (s = emacsShift) the product DOES NOT")
(println "    EXIST for any a /= identity. Not 'is hard to find' — there is no")
(println "    policy satisfying the constraint. My earlier orbit printed rows")
(println "    anyway because last-write-wins hid the contradiction.")
(println "    Under the POINTWISE reading (s = identity) it always exists and is")
(println "    trivial: g' = a . g, period = ord(a). But s = id is SURJECTIVE, so")
(println "    FREE = {} — no scaffold. free_nonempty_iff_not_surjective says that")
(println "    is the degenerate case.")
(println "    So the two readings fail in OPPOSITE ways: the one with a scaffold")
(println "    has no solution; the one with a solution has no scaffold.")
