; Generated by futon7/scripts/r-cascade-draw.bb; r-cascade-ruled.edn sha256=f3b3111473fa1295615e8b4e576a598e4f636d7c2562a9141bb64f920c70f39d; control-stages.edn sha256=9d87c52e1e87f17fd3283a8beb2e73e8ae37852bc78c4ebcaa5f641af20b8f47
; A multiply-parented unit is expanded at its first depth-first occurrence and written `(ref UNIT)` thereafter.
(click-input
  (R13
    (CTAU-CLASS)
    (CTAU-TOKEN)
    (R4))
  (R14
    (R6-select
      (R16)))
  (R19
    (R5
      (ref R6-select)))
  (R2
    (R1
      (R17
        (ref R6-select)
        (SCAN))
      (R3a
        (R3))
      (ref R4))
    (R6-candidates
      (ref R17)
      (ref R4)
      (R8
        (ref R6-select))))
  (R7
    (ref R17)
    (ref R4)))
