#!/usr/bin/env bb
;; merge_edges.bb — assemble p4ng/empirics-futon/hyper-edge-schema.edn's :instances
;; from per-edge fragments, so N edge-units can be written in parallel.
;;
;; Same defect as the witness registry: :instances is ONE vector every edge-unit appends
;; to. The schema header (:schema/version, :required/*, :rules) is hand-authored and stays
;; in place; only :instances is generated.
;;
;;   --split   one-time: explode current :instances into fragments
;;   --check   merge in memory and compare against the committed file
;;   (default) merge fragments -> :instances
(require '[clojure.java.io :as io] '[clojure.pprint :as pp] '[clojure.string :as str])

(def schema "/home/joe/code/p4ng/empirics-futon/hyper-edge-schema.edn")
(def frag-dir "/home/joe/code/p4ng/empirics-futon/edge-fragments")

(defn frag-name [i] (str (str/replace (str (:edge/id i)) #"[^A-Za-z0-9_.-]" "_") ".edn"))

(defn read-frags []
  (->> (.listFiles (io/file frag-dir))
       (filter #(str/ends-with? (.getName %) ".edn"))
       (sort-by #(.getName %))
       (map #(read-string (slurp %)))))

(defn merged-instances []
  (let [is (read-frags)
        ids (map :edge/id is)
        dupes (->> ids frequencies (filter (fn [[_ n]] (< 1 n))) (map first))]
    (when (seq dupes)
      (println "DUPLICATE :edge/id across fragments:" (pr-str dupes)) (System/exit 1))
    (vec is)))

(defn -main [& args]
  (let [doc (read-string (slurp schema))]
    (cond
      (some #{"--split"} args)
      (do (doseq [i (:instances doc)] (spit (str frag-dir "/" (frag-name i)) (with-out-str (pp/pprint i))))
          (println "split" (count (:instances doc)) "instances into" frag-dir))

      (some #{"--check"} args)
      (let [a (:instances doc) b (merged-instances)]
        (if (= (set a) (set b))
          (println (pr-str {:pass? true :instances (count b) :note "merge(fragments) == committed :instances"}))
          (do (println (pr-str {:pass? false :committed (count a) :merged (count b)
                                :only-committed (mapv :edge/id (remove (set b) a))
                                :only-merged (mapv :edge/id (remove (set a) b))}))
              (System/exit 1))))

      :else
      (let [b (merged-instances)
            hdr (str ";; :instances are GENERATED by futon2/scripts/merge_edges.bb — DO NOT HAND-EDIT them.\n"
                     ";; Add or edit a fragment in empirics-futon/edge-fragments/ and re-run the merge.\n"
                     ";; Fragments exist so N edge-units can be written in parallel without N-way conflict\n"
                     ";; on one vector (build plan 2026-08-31). The schema header above :instances is\n"
                     ";; hand-authored and is preserved verbatim by the merge.\n")]
        (spit schema (str hdr (with-out-str (pp/pprint (assoc doc :instances b)))))
        (println "merged" (count b) "fragments ->" schema)))))

(when (= *file* (System/getProperty "babashka.file")) (apply -main *command-line-args*))
