#!/usr/bin/env bb
;; merge_witnesses.bb — assemble checks/witness-registry.edn from per-unit fragments.
;;
;; Why: 14 bind-hole units all append to one EDN vector. Fourteen agents editing one
;; file on a shared checkout is fourteen-way conflict, so the plan was sequential no
;; matter how many agents existed. Each unit now writes its OWN fragment
;; (checks/witness-fragments/<id>.edn) and this merges them. Parallel-safe by construction.
;;
;;   --split   one-time: explode the current registry into fragments
;;   --check   merge in memory and diff against the committed registry (round-trip test)
;;   (default) merge fragments -> registry
(require '[clojure.java.io :as io] '[clojure.pprint :as pp] '[clojure.string :as str])

(def frag-dir "checks/witness-fragments")
(def registry "checks/witness-registry.edn")

(defn frag-name [e]
  (let [w (:witnesses e), w (if (string? w) [w] w)]
    (str (str/replace (or (first w) "unnamed") #"[^A-Za-z0-9_.-]" "_") ".edn")))

(defn read-frags []
  (->> (.listFiles (io/file frag-dir))
       (filter #(str/ends-with? (.getName %) ".edn"))
       (sort-by #(.getName %))
       (map #(read-string (slurp %)))))

(defn merged []
  (let [es (read-frags)
        wits (mapcat #(let [w (:witnesses %)] (if (string? w) [w] w)) es)
        dupes (->> wits frequencies (filter (fn [[_ n]] (< 1 n))) (map first))]
    (when (seq dupes)
      (println "DUPLICATE witness names across fragments:" (pr-str dupes))
      (System/exit 1))
    (vec es)))

(defn -main [& args]
  (cond
    (some #{"--split"} args)
    (let [es (read-string (slurp registry))]
      (doseq [e es] (spit (str frag-dir "/" (frag-name e)) (with-out-str (pp/pprint e))))
      (println "split" (count es) "entries into" frag-dir))

    (some #{"--check"} args)
    (let [a (read-string (slurp registry)) b (merged)]
      (if (= (set a) (set b))
        (println (pr-str {:pass? true :entries (count b) :note "merge(fragments) == committed registry"}))
        (do (println (pr-str {:pass? false :registry (count a) :merged (count b)
                              :only-in-registry (vec (remove (set b) a))
                              :only-in-merged (vec (remove (set a) b))}))
            (System/exit 1))))

    :else
    (let [b (merged)
          hdr (str ";; GENERATED by scripts/merge_witnesses.bb — DO NOT HAND-EDIT.\n"
                   ";; Edit or add a fragment in checks/witness-fragments/ and re-run the merge.\n"
                   ";; Fragments exist so that N units can be written in parallel without N-way\n"
                   ";; conflict on one EDN vector (build plan 2026-08-31, wave 1).\n")]
      (spit registry (str hdr (with-out-str (pp/pprint b))))
      (println "merged" (count b) "fragments ->" registry))))

(when (= *file* (System/getProperty "babashka.file")) (apply -main *command-line-args*))
